version: '3.1'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - app-datas:/app
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev
            MONGO_INITDB_ROOT_PASSWORD: 1234
        networks:
            - app-network
        volumes:
            - app-datas:/database

networks:
    app-network:
        driver: bridge

volumes:
    app-datas:
