/user:
    get:
        description: Get user
        tags:
            - user
        responses:
            200:
                description: Successful response
    post:
        description: Create user
        tags:
            - user
